/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'bus' : IDL.Null,
  'cab' : IDL.Null,
  'van' : IDL.Null,
  'truck' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'destination' : IDL.Text,
  'netAmount' : IDL.Nat,
  'ratePerKm' : IDL.Nat,
  'endingKm' : IDL.Nat,
  'totalKm' : IDL.Nat,
  'startingKm' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'dieselOrGasByCustomer' : IDL.Nat,
  'updatedAt' : Time,
  'totalAmount' : IDL.Nat,
  'tollTax' : IDL.Nat,
  'customerNo' : IDL.Text,
  'dateTime' : Time,
  'vehicleId' : IDL.Nat,
  'vehicleNo' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'vehicleType' : VehicleType,
  'isAvailable' : IDL.Bool,
  'currentLocation' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVehicle' : IDL.Func([VehicleType, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'completeBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAvailableVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setVehicleAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(Time),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateVehicle' : IDL.Func(
      [IDL.Nat, IDL.Opt(VehicleType), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateVehicleLocation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'bus' : IDL.Null,
    'cab' : IDL.Null,
    'van' : IDL.Null,
    'truck' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'destination' : IDL.Text,
    'netAmount' : IDL.Nat,
    'ratePerKm' : IDL.Nat,
    'endingKm' : IDL.Nat,
    'totalKm' : IDL.Nat,
    'startingKm' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'dieselOrGasByCustomer' : IDL.Nat,
    'updatedAt' : Time,
    'totalAmount' : IDL.Nat,
    'tollTax' : IDL.Nat,
    'customerNo' : IDL.Text,
    'dateTime' : Time,
    'vehicleId' : IDL.Nat,
    'vehicleNo' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'vehicleType' : VehicleType,
    'isAvailable' : IDL.Bool,
    'currentLocation' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVehicle' : IDL.Func([VehicleType, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'completeBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAvailableVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setVehicleAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(Time),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateVehicle' : IDL.Func(
        [IDL.Nat, IDL.Opt(VehicleType), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateVehicleLocation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };