/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'destination' : string,
  'netAmount' : bigint,
  'ratePerKm' : bigint,
  'endingKm' : bigint,
  'totalKm' : bigint,
  'startingKm' : bigint,
  'createdAt' : Time,
  'user' : Principal,
  'dieselOrGasByCustomer' : bigint,
  'updatedAt' : Time,
  'totalAmount' : bigint,
  'tollTax' : bigint,
  'customerNo' : string,
  'dateTime' : Time,
  'vehicleId' : bigint,
  'vehicleNo' : string,
  'pickupLocation' : string,
}
export type BookingStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : bigint,
  'vehicleType' : VehicleType,
  'isAvailable' : boolean,
  'currentLocation' : string,
}
export type VehicleType = { 'bus' : null } |
  { 'cab' : null } |
  { 'van' : null } |
  { 'truck' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVehicle' : ActorMethod<[VehicleType, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'completeBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [
      bigint,
      Time,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    bigint
  >,
  'deleteVehicle' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAvailableVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[bigint], [] | [Vehicle]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setVehicleAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'updateBooking' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      [] | [Time],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'updateVehicle' : ActorMethod<
    [bigint, [] | [VehicleType], [] | [string]],
    undefined
  >,
  'updateVehicleLocation' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];